### ISSUE TITLE
Switch to System.Numerics.BigInteger

### ISSUE THREAD

**Issue by bazzilic** [bazzilic/ElGamalExt#8]
Switch this library to use `System.Numerics.BigInteger` instead of our own implementation of big integer arithmetics—`BigInteger`.

**Comment by Nicholas-Chew** [comment]
I am doing Unit Testing against own implementation of Big Integer. Do I need to commit the Testing and Implementation? Where should I commit?

**Comment by Nicholas-Chew** [comment]
One more question. Would you like to retain the main code as much as possible in the ```ElGamalExt```?
Example would be ```a.modPow(exp, mod)``` which is the original one compare to ```BigInteger.ModPow(base, exp, mod)```

**Comment by bazzilic** [comment]
> I am doing Unit Testing against own implementation of Big Integer

What is "own implementation"? There are unit tests in the project to check whether everything works correct after changes. They, of course, rely on the old `BigInteger`, so they need to be updated too.

> Where should I commit?

Commit in your fork, after which make a pull request.

> Would you like to retain the main code as much as possible

Tbh, the example did bot make your question more clear.

**Comment by Nicholas-Chew** [comment]
Apologies. I will rephrase my questions.
> What is "own implementation"? There are unit tests in the project to check whether everything works correct after changes. They, of course, rely on the old BigInteger, so they need to be updated too.
>
I am doing Unit Testing the new implementation using the `old BigInteger` for the new implementation will yield the same result. Hence, the Unit Testing involving the `old BigInteger` and the `new BigInteger`. 
My question is do I need to commit the Unit Testing as it involves `ElGamalExt.BigInt` (This is how I named it) and `BigInteger` (old implementation) and where should I commit as it involves two modules.

> Tbh, the example did bot make your question more clear.
>
For example, in `ElGamalDecryptor`. To do a Modular Power we can call a function from the object direction which is `aBigIntObj.modPow(exponent, modular)`, However, `System.Numeric.BigInteger` dosent have this function. The function is only exposed through `System.Numeric.BigInteger.ModPow`.
Which my question is do you prefer to retain the original code as much as possible as it is possible to create a function to do `modPow` (example) directly from the object? Hence, there will be least changes in the original code.

**Comment by bazzilic** [comment]
Regarding the first question, for now leave the testing project as is, using the old BigInteger.

Regarding the second question, there's no need to retain as much old code as possible, use the class as it is intended to be used.

**Comment by Nicholas-Chew** [comment]
I will need some more time. All other operations are good and tested except for `genRandomBits` and `genPseudoPrime`.

**Comment by Nicholas-Chew** [comment]
I am having some issue with the Unit Test when integrating the new BigInteger into ElGamalExt. However, the Unit Test for individual functions are good. May I know is ElGamalExt's unit test passed with the old BigInteger Implementation?

**Comment by bazzilic** [comment]
It should have, or otherwise the AppVeyor build would fail. You can check for yoursel: do a `git checkout` from the master branch or from the original commit if you develop in the same branch. You can use `git log --oneline --graph --decorate` to find the commit.
